import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const router = useRouter();
  const [nickname, setNickname] = useState("");

  return (
    <>
      <Head>
        <title>NooN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <p>
          게임을 플레이하면 할수록 <br />
          시각장애인을 위해 이미지를 읽어주는 <br />눈 인공지능이 똑똑해져요
        </p>
        <p>오늘까지 쌓인 눈송이 총 000개</p>
        <p>000명이 참여하고 있어요.</p>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            alert(nickname);
            router.push("/question");
          }}
        >
          <input
            id="nickname"
            name="nickname"
            placeholder="닉네임을 입력하세요"
            value={nickname}
            onChange={(e) => setNickname(e.target.value)}
          />
          <ul>
            <li>1등 닉네임 00개</li>
            <li>2등 닉네임 00개</li>
            <li>3등 닉네임 00개</li>
          </ul>
          <button type="button">플레이 하러 가기</button>
        </form>
      </main>
      <footer>
        <Image
          priority
          src="/logo.png"
          alt="NooN 로고"
          width={327}
          height={93}
        />
      </footer>
    </>
  );
};

export default Home;
