import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/router";
import useAuth from "../hooks/useAuth";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const router = useRouter();
  const [nickname, setNickname] = useState("");

  /*const [trigger, setTrigger] = useState(false);*/

  const { generateUser } = useAuth();
  const handleSubmit = () => {
    const refinedNickname = nickname.trim();
    if (refinedNickname.length === 0) return;

    generateUser(refinedNickname);
    void router.push("/questions");
  };

  return (
    <>
      <Head>
        <title>NooN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
<<<<<<< Updated upstream
        <Image
          priority
          src="/logo.png"
          alt="NooN 로고"
          width={225}
          height={70}
        />
        <p>
          모두에게 이로운 <br /> 대한민국 웹접근성 개선 프로젝트
        </p>
        <p>
          게임을 플레이하면 할수록 <br />
          시각장애인을 위해 이미지를 읽어주는
          <br />눈 NooN 인공지능이 똑똑해져요
        </p>
        <p>더 많은 사람들이 선택한 대체텍스트*를 찾아 보세요!</p>
        <p>누적 점수 총 000점</p>
        <p>000명이 참여하고 있어요.</p>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSubmit();
          }}
        >
          <input
            id="nickname"
            name="nickname"
            placeholder="닉네임을 입력하세요"
            value={nickname}
            onChange={(e) => {
              setNickname(e.target.value);
            }}
          />
          <button>시작하기</button>
        </form>
        <a href="">NooN 확장 프로그램 써 보러 가기</a>
=======
        <div className="area" >
          <ul className="circles">
            <li></li>
            <li></li>
            <li></li>
          </ul>

          <div className="middle">
            <div className="ranking">
              <ul>
                <li>1등 닉네임닉  00벌</li>
                <li>2등 닉네임닉  00벌</li>
                <li>3등 닉네임닉  00벌</li>
                <li>4등 닉네임닉  00벌</li>
              </ul>
            </div>
            <div className="impact">
              <p>총 000벌을 읽었어요!</p>
            </div>  
            <div className="imgAlign">
            <Image
              priority
              src="/logo.png"
              alt="NooN 로고"
              width={382}
              height={122}
            />
            </div>

            <div className="subTitle">
            <Image
              priority
              src="/sublogo.png"
              alt="for Fashion"
              width={207}
              height={99}
            />
            </div>
            <p>패션을 들려주는 새로운 눈</p>

            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleSubmit();
              }}
            >
              <input
                id="nickname"
                name="nickname"
                placeholder="닉네임을 입력하세요"
                value={nickname}
                onChange={(e) => {
                  setNickname(e.target.value);
                }}
              />
              <p>더 많은 사람들이 선택한 대체텍스트*를 찾아 보세요!</p>
              <button>시작하기</button>
            </form>

          </div>
          <div className="right">
            <a href="www.google.com">NooN 확장 프로그램 써 보러 가기</a>
          </div>
        
        </div >

>>>>>>> Stashed changes
      </main>
      <style jsx>{`
        body{
          background: white;
          font-family: 'SCoreDream';
        }
        .middle{
          text-align: center;
        }
        .right{
          position: absolute;
          bottom: 0;
          right: 0;
          margin: 15px;
        }
        .ranking{
        }
        .impact{
          font-family: 'SCoreDream';
          font-style: normal;
          font-weight: 600;
          font-size: 30px;
          line-height: 36px;
          margin: 20px;
        }
        .imgAlign{
          display: flex;
          justify-content: center;
          mix-blend-mode: difference;
        }
        .subTitle{
          display: flex;
          justify-content: center;
          mix-blend-mode: difference;
          margin: 10px;
        }


        /** background css */
        .area{
          z-index: -2;
          padding: 50px;
          width: 100%;
          height:100%;
          }
      
        .circles{
            z-index: -1;
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
        }
        
        .circles li{
            position: absolute;
            display: block;
            list-style: none;
            background: rgba(234, 238, 38, 0.9);
            animation: animate 25s infinite ease-in;
            bottom: -150px;
        }
        
        .circles li:nth-child(1){
            left: 140%;
            width: 1547px;
            height: 1400px;
            transform: rotate(45deg);
            animation-delay: 0s;
            animation-duration: 45s;
        }
        
        .circles li:nth-child(2){
            left: 10%;
            width: 800px;
            height: 700px;
            animation-duration: 35s;
        }
        
        .circles li:nth-child(3){
            left: -10%;
            width: 500px;
            height: 400px;
            animation-duration: 23s;
        }
        
        @keyframes animate {  
            0%{
                top: -1000px; left: -500px;
                transform: rotate(0deg);
                opacity: 1;
                border-radius: 50%;
            }
            50%{
                top: 200px; left: 50px; 
                transform: rotate(360deg);
                opacity: 0.5;
                border-radius: 100%;
            }
            100%{
                top: -1000px; left: -500px;
                transform: rotate(720deg);
                opacity: 1;
                border-radius: 80%;
            }
        }
      `}
      </style>
    </>
  );
};

export default Home;
