import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/router";
import useAuth from "../hooks/useAuth";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const router = useRouter();
  const [nickname, setNickname] = useState("");

  const { generateUser } = useAuth();
  const handleSubmit = () => {
    const refinedNickname = nickname.trim();
    if (refinedNickname.length === 0) return;

    generateUser(refinedNickname);
    void router.push("/questions");
  };

  return (
    <>
      <Head>
        <title>NooN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          priority
          src="/logo.png"
          alt="NooN 로고"
          width={225}
          height={70}
        />
        <p>
          모두에게 이로운 <br /> 대한민국 웹접근성 개선 프로젝트
        </p>
        <p>
          게임을 플레이하면 할수록 <br />
          시각장애인을 위해 이미지를 읽어주는
          <br />눈 NooN 인공지능이 똑똑해져요
        </p>
        <p>더 많은 사람들이 선택한 대체텍스트*를 찾아 보세요!</p>
        <p>누적 점수 총 000점</p>
        <p>000명이 참여하고 있어요.</p>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSubmit();
          }}
        >
          <input
            id="nickname"
            name="nickname"
            placeholder="닉네임을 입력하세요"
            value={nickname}
            onChange={(e) => {
              setNickname(e.target.value);
            }}
          />
          <button>시작하기</button>
        </form>
        <a href="">NooN 확장 프로그램 써 보러 가기</a>
      </main>
    </>
  );
};

export default Home;
