import { type NextPage } from "next";
import Head from "next/head";
import Carousel from "../foundations/Carousel";
import Link from "next/link";
import useSWR from "swr";
import { type AnsweredQuestion, QUESTIONS_KEY } from "./questions";
import useAuth from "../hooks/useAuth";

const Inspect: NextPage = () => {
  const { uuid, nickname } = useAuth();
  const { data: questions } = useSWR<AnsweredQuestion[]>(QUESTIONS_KEY);
  console.log(questions);

  return (
    <>
      <Head>
        <title>검수 - NooN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>
          보이지 않아도 글을 듣고 어떤 상품인지 알 수 있다면 옷장에 담아주세요.
          혹시 방금 본 아이템들 중 설명이 부적절한 대체텍스트는 없었나요? 옷장에
          담기 전, {nickname}님이 직접 대체텍스트를 수정할 수 있어요!
        </p>
        <div className="carouselWrapper">
          {questions && (
            <Carousel
              fullWidth={833}
              fullHeight={650}
              items={new Array(9).fill(null).map((_, i) => {
                const option = questions[i % questions.length];
                return (
                  <div className="mock" key={i}>
                    <img
                      className="image"
                      src={option?.url || ""}
                      alt={option?.correctAnswer || ""}
                      width={500}
                      height={500}
                    />
                  </div>
                );
              })}
              emitCurrentIndex={(index) => {
                console.log(index);
              }}
            />
          )}
          <button>이 아이템 옷장에 집어넣기</button>
        </div>
        <Link href="/score">넘어 가기</Link>
      </main>
      <style jsx>{`
        .carouselWrapper {
          display: flex;
          justify-content: center;
          align-items: center;
          flex-direction: column;

          max-width: 1000px;
          width: 100%;
          height: 100%;
          overflow: hidden;
        }
        .mock {
          width: 500px;
          height: 500px;
          background: black;
          border-radius: 10px;
        }
        .image {
          width: 100%;
          height: 100%;
          object-fit: cover;
          user-select: none;
          -webkit-user-drag: none;
          border-radius: 10px;
        }
      `}</style>
    </>
  );
};

export default Inspect;
