import { type NextPage } from "next";
import Head from "next/head";

import Image from "next/image";
import useAuth from "../hooks/useAuth";
import { api } from "../utils/api";
import { useState } from "react";

const Questions: NextPage = () => {
  const { data: question } = api.question.randomQuestion.useQuery();

  // const { uuid, nickname } = useAuth();

  const [answer, setAnswer] = useState<null | number>(null);
  const sum =
    question?.options?.reduce((prev, option) => prev + option.submitCount, 0) ??
    0;

  return (
    <>
      <Head>
        <title>문제 - NooN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          priority
          src="/logo.png"
          alt="NooN logo"
          width={327}
          height={93}
        />
        <p>000점</p>

        {question && (
          <>
            <Image
              priority
              src={question.url}
              alt="MOCK"
              width={320}
              height={280}
              style={{ objectFit: "contain" }}
            />
            <p>
              눈이 보이지 않는 사람에게 위 이미지를 설명해 봅시다. 사람들은 어떤
              선택지를 가장 많이 골랐을까요?
            </p>
            {question.options.map((option, index) => (
              <div
                className="box"
                key={option.id}
                onClick={() => setAnswer(option.id)}
              >
                <span className="text">{option.text}</span>
                <span className="number">{index + 1}</span>
                <span
                  className="percent"
                  style={{
                    transform: `scaleX(${
                      answer ? option.submitCount / sum : 0
                    })`,
                  }}
                />
              </div>
            ))}
          </>
        )}
      </main>
      <style jsx>{`
        .box {
          position: relative;
          max-width: 340px;
          min-height: 50px;
          padding: 20px;

          background: #ffffff;
          border: 1px solid #000000;
          border-radius: 10px;
        }
        .text {
          position: relative;
          color: white;
          mix-blend-mode: difference;
          z-index: 1;
        }
        .number {
          position: absolute;
          top: 0;
          left: 0;
          width: 19px;
          height: 22px;
          border-radius: 8.5px 0 6px;
          z-index: 1;

          color: black;
          mix-blend-mode: difference;
          background: white;
          background-blend-mode: difference;
        }
        .percent {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          border-radius: 10px;

          transition: transform 1s;
          background-color: black;
          transform-origin: left;
        }
      `}</style>
    </>
  );
};

export default Questions;
