import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import Image from "next/image";

const Questions: NextPage = () => {
  const { data: question } = api.question.randomQuestion.useQuery();

  console.log(question);

  return (
    <>
      <Head>
        <title>문제 - NooN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <p>눈송이 00개</p>
      </main>
      <footer>
        <Image
          priority
          src="/logo.png"
          alt="NOON logo"
          width={327}
          height={93}
        />
      </footer>
    </>
  );
};

export default Questions;
