import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import useAuth from "../hooks/useAuth";
import { useRouter } from "next/router";

const Score: NextPage = () => {
  const { data: ranking } = api.ranking.get.useQuery();
  const { retryUser, uuid, nickname } = useAuth();
  const me = ranking?.find((ele) => ele.userUuid === uuid);

  const router = useRouter();
  const retry = () => {
    retryUser();
    void router.push("/questions");
  };

  return (
    <>
      <Head>
        <title>점수 - NooN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>
          {nickname} 님, 총 {me?.score}벌
        </p>
        <p>
          {ranking?.length}명 중에 {me?.rank}등!
        </p>
        <p>
          {nickname}님 덕분에 눈 NooN 이 패션을 더 잘 들려줄 수 있게 되었어요
          감사해요 :)
        </p>
        <button onClick={retry}>다시 시작하기</button>
      </main>
      <style jsx>{`
        button {
          border: 1px solid black;
        }
      `}</style>
    </>
  );
};

export default Score;
